// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwmggIXG-wHw8zclFje9-QI8KHkNaQqd4',
    appId: '1:148935883756:web:711127da201bcc77d79ec9',
    messagingSenderId: '148935883756',
    projectId: 'mabarin-c1d84',
    authDomain: 'mabarin-c1d84.firebaseapp.com',
    storageBucket: 'mabarin-c1d84.appspot.com',
    measurementId: 'G-M7DMZQQ0P9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLlL1u0zf_PZvC87-Q7nqg2GX3cVQ6M4Q',
    appId: '1:148935883756:android:0714815111442675d79ec9',
    messagingSenderId: '148935883756',
    projectId: 'mabarin-c1d84',
    storageBucket: 'mabarin-c1d84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJLwUKqd71uyJdcqypz8NbjN_EXiyLyyY',
    appId: '1:148935883756:ios:b4bb62fee44c9fe6d79ec9',
    messagingSenderId: '148935883756',
    projectId: 'mabarin-c1d84',
    storageBucket: 'mabarin-c1d84.appspot.com',
    iosBundleId: 'com.example.mabarinApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJLwUKqd71uyJdcqypz8NbjN_EXiyLyyY',
    appId: '1:148935883756:ios:b4bb62fee44c9fe6d79ec9',
    messagingSenderId: '148935883756',
    projectId: 'mabarin-c1d84',
    storageBucket: 'mabarin-c1d84.appspot.com',
    iosBundleId: 'com.example.mabarinApp',
  );
}
